app:
  debugapi: true

mysql:
  host: mysql
  hostm: mysql
  dbname: userdb
  user: scott
  password: tiger
  usecache: true

pgsql:
  host: pgsql
  dbname: logdb
  user: scott
  password: tiger

redis:
  host: redis

dynamodb:
  endpoint: http://dynamodb:8000
  key: dummy
  secret: dummy
  table: hogehoge

storage:
  endpoint: http://storage:9000
  key: s3accesskey
  secret: s3secretkey
  bucket: dummy

sqs:
  endpoint: http://sqs:9324
  key: hoge
  secret: fuga

logger:
  type: fluent
  host: fluentd:24224

serializer:
  type: json

#logger:
#  type: sqs
#  queue: http://sqs:9324/queue/hoge_queue
