version: '3'

services:
  proxy:
    build:
      context: ./proxy
      args:
        - environment=local
    ports:
      - "80:3128"
      - "443:8443"
    volumes:
      - ../certs:/etc/certs:ro
    container_name: proxy
    networks:
      - private_net
    depends_on:
      - "web_app"
      - "web_mgr"

  web_app:
    build:
      context: ..
      dockerfile: compose/web_app/Dockerfile
      args:
        - environment=local
    volumes:
      - ../code/app/src:/var/www/app/src
      - ../code/app/public:/var/www/app/public
      - ../code/common/src:/var/www/common/src
      - ../code/vendor:/var/www/vendor
    container_name: web_app
    networks:
      - private_net
    environment:
      XDEBUG_CONFIG: "remote_host=172.28.0.1"
      PHP_IDE_CONFIG: "serverName=app.localhost"

  web_mgr:
    build:
      context: ..
      dockerfile: compose/web_mgr/Dockerfile
      args:
        - environment=local
    volumes:
      - ../code/mgr/src:/var/www/mgr/src
      - ../code/mgr/public:/var/www/mgr/public
      - ../code/common/src:/var/www/common/src
      - ../code/vendor:/var/www/vendor
    container_name: web_mgr
    networks:
      - private_net
    environment:
      XDEBUG_CONFIG: "remote_host=172.28.0.1"
      PHP_IDE_CONFIG: "serverName=mgr.localhost"

  redis:
    image: redis:5.0.5
    container_name: redis
    ports:
      - "16379:6379"
    networks:
      - private_net
    volumes:
      - redis-data:/var/lib/redis
    sysctls:
      - net.core.somaxconn=1024

  mysql:
    build:
      context: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "13306:3306"
    container_name: mysql
    networks:
      - private_net

  pgsql:
    build:
      context: ./pgsql
    volumes:
      - pgsql-data:/var/lib/postgresql
    ports:
      - "15432:5432"
    container_name: pgsql
    networks:
      - private_net

  dynamodb:
    build:
      context: ./dynamodb
    volumes:
      - dynamodb-data:/data
    container_name: dynamodb
    ports:
      - "18000:8000"
    networks:
      - private_net

  storage:
    image: minio/minio
    volumes:
      - storage-data:/data
    container_name: storage
    ports:
      - "19000:9000"
    environment:
      MINIO_ACCESS_KEY: s3accesskey
      MINIO_SECRET_KEY: s3secretkey
    command: server /data
    networks:
      - private_net

  sqs:
    build:
      context: ./sqs
    ports:
      - "19324:9324"
    container_name: sqs
    networks:
      - private_net

  fluentd:
    build:
      context: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
    networks:
      - private_net

volumes:
  redis-data:
  mysql-data:
  pgsql-data:
  storage-data:
  dynamodb-data:

networks:
  private_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
